//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Este código-fonte foi gerado automaticamente por Microsoft.VSDesigner, Versão 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ConsumindoSOAP.Servico2 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wsConsultaSQLSoap", Namespace="http://www.totvs.com.br/br/")]
    public partial class wsConsultaSQL : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AutenticaAcessoAuthOperationCompleted;
        
        private System.Threading.SendOrPostCallback AutenticaAcessoOperationCompleted;
        
        private System.Threading.SendOrPostCallback RealizarConsultaSQLDataTableOperationCompleted;
        
        private System.Threading.SendOrPostCallback RealizarConsultaSQLDataTableAuthOperationCompleted;
        
        private System.Threading.SendOrPostCallback RealizarConsultaSQLOperationCompleted;
        
        private System.Threading.SendOrPostCallback RealizarConsultaSQLAuthOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wsConsultaSQL() {
            this.Url = global::ConsumindoSOAP.Properties.Settings.Default.ConsumindoSOAP_Servico2_wsConsultaSQL;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AutenticaAcessoAuthCompletedEventHandler AutenticaAcessoAuthCompleted;
        
        /// <remarks/>
        public event AutenticaAcessoCompletedEventHandler AutenticaAcessoCompleted;
        
        /// <remarks/>
        public event RealizarConsultaSQLDataTableCompletedEventHandler RealizarConsultaSQLDataTableCompleted;
        
        /// <remarks/>
        public event RealizarConsultaSQLDataTableAuthCompletedEventHandler RealizarConsultaSQLDataTableAuthCompleted;
        
        /// <remarks/>
        public event RealizarConsultaSQLCompletedEventHandler RealizarConsultaSQLCompleted;
        
        /// <remarks/>
        public event RealizarConsultaSQLAuthCompletedEventHandler RealizarConsultaSQLAuthCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.totvs.com.br/br/AutenticaAcessoAuth", RequestNamespace="http://www.totvs.com.br/br/", ResponseNamespace="http://www.totvs.com.br/br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AutenticaAcessoAuth(string Usuario, string Senha) {
            object[] results = this.Invoke("AutenticaAcessoAuth", new object[] {
                        Usuario,
                        Senha});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AutenticaAcessoAuthAsync(string Usuario, string Senha) {
            this.AutenticaAcessoAuthAsync(Usuario, Senha, null);
        }
        
        /// <remarks/>
        public void AutenticaAcessoAuthAsync(string Usuario, string Senha, object userState) {
            if ((this.AutenticaAcessoAuthOperationCompleted == null)) {
                this.AutenticaAcessoAuthOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAutenticaAcessoAuthOperationCompleted);
            }
            this.InvokeAsync("AutenticaAcessoAuth", new object[] {
                        Usuario,
                        Senha}, this.AutenticaAcessoAuthOperationCompleted, userState);
        }
        
        private void OnAutenticaAcessoAuthOperationCompleted(object arg) {
            if ((this.AutenticaAcessoAuthCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AutenticaAcessoAuthCompleted(this, new AutenticaAcessoAuthCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.totvs.com.br/br/AutenticaAcesso", RequestNamespace="http://www.totvs.com.br/br/", ResponseNamespace="http://www.totvs.com.br/br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AutenticaAcesso() {
            object[] results = this.Invoke("AutenticaAcesso", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AutenticaAcessoAsync() {
            this.AutenticaAcessoAsync(null);
        }
        
        /// <remarks/>
        public void AutenticaAcessoAsync(object userState) {
            if ((this.AutenticaAcessoOperationCompleted == null)) {
                this.AutenticaAcessoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAutenticaAcessoOperationCompleted);
            }
            this.InvokeAsync("AutenticaAcesso", new object[0], this.AutenticaAcessoOperationCompleted, userState);
        }
        
        private void OnAutenticaAcessoOperationCompleted(object arg) {
            if ((this.AutenticaAcessoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AutenticaAcessoCompleted(this, new AutenticaAcessoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.totvs.com.br/br/RealizarConsultaSQLDataTable", RequestNamespace="http://www.totvs.com.br/br/", ResponseNamespace="http://www.totvs.com.br/br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable RealizarConsultaSQLDataTable(string codSentenca, int codColigada, string codSistema, string codUsuario, string parameters) {
            object[] results = this.Invoke("RealizarConsultaSQLDataTable", new object[] {
                        codSentenca,
                        codColigada,
                        codSistema,
                        codUsuario,
                        parameters});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void RealizarConsultaSQLDataTableAsync(string codSentenca, int codColigada, string codSistema, string codUsuario, string parameters) {
            this.RealizarConsultaSQLDataTableAsync(codSentenca, codColigada, codSistema, codUsuario, parameters, null);
        }
        
        /// <remarks/>
        public void RealizarConsultaSQLDataTableAsync(string codSentenca, int codColigada, string codSistema, string codUsuario, string parameters, object userState) {
            if ((this.RealizarConsultaSQLDataTableOperationCompleted == null)) {
                this.RealizarConsultaSQLDataTableOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRealizarConsultaSQLDataTableOperationCompleted);
            }
            this.InvokeAsync("RealizarConsultaSQLDataTable", new object[] {
                        codSentenca,
                        codColigada,
                        codSistema,
                        codUsuario,
                        parameters}, this.RealizarConsultaSQLDataTableOperationCompleted, userState);
        }
        
        private void OnRealizarConsultaSQLDataTableOperationCompleted(object arg) {
            if ((this.RealizarConsultaSQLDataTableCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RealizarConsultaSQLDataTableCompleted(this, new RealizarConsultaSQLDataTableCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.totvs.com.br/br/RealizarConsultaSQLDataTableAuth", RequestNamespace="http://www.totvs.com.br/br/", ResponseNamespace="http://www.totvs.com.br/br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable RealizarConsultaSQLDataTableAuth(string codSentenca, int codColigada, string codAplicacao, string Usuario, string Senha, string parameters) {
            object[] results = this.Invoke("RealizarConsultaSQLDataTableAuth", new object[] {
                        codSentenca,
                        codColigada,
                        codAplicacao,
                        Usuario,
                        Senha,
                        parameters});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void RealizarConsultaSQLDataTableAuthAsync(string codSentenca, int codColigada, string codAplicacao, string Usuario, string Senha, string parameters) {
            this.RealizarConsultaSQLDataTableAuthAsync(codSentenca, codColigada, codAplicacao, Usuario, Senha, parameters, null);
        }
        
        /// <remarks/>
        public void RealizarConsultaSQLDataTableAuthAsync(string codSentenca, int codColigada, string codAplicacao, string Usuario, string Senha, string parameters, object userState) {
            if ((this.RealizarConsultaSQLDataTableAuthOperationCompleted == null)) {
                this.RealizarConsultaSQLDataTableAuthOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRealizarConsultaSQLDataTableAuthOperationCompleted);
            }
            this.InvokeAsync("RealizarConsultaSQLDataTableAuth", new object[] {
                        codSentenca,
                        codColigada,
                        codAplicacao,
                        Usuario,
                        Senha,
                        parameters}, this.RealizarConsultaSQLDataTableAuthOperationCompleted, userState);
        }
        
        private void OnRealizarConsultaSQLDataTableAuthOperationCompleted(object arg) {
            if ((this.RealizarConsultaSQLDataTableAuthCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RealizarConsultaSQLDataTableAuthCompleted(this, new RealizarConsultaSQLDataTableAuthCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.totvs.com.br/br/RealizarConsultaSQL", RequestNamespace="http://www.totvs.com.br/br/", ResponseNamespace="http://www.totvs.com.br/br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RealizarConsultaSQL(string codSentenca, int codColigada, string codAplicacao, string codUsuario, string parameters) {
            object[] results = this.Invoke("RealizarConsultaSQL", new object[] {
                        codSentenca,
                        codColigada,
                        codAplicacao,
                        codUsuario,
                        parameters});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RealizarConsultaSQLAsync(string codSentenca, int codColigada, string codAplicacao, string codUsuario, string parameters) {
            this.RealizarConsultaSQLAsync(codSentenca, codColigada, codAplicacao, codUsuario, parameters, null);
        }
        
        /// <remarks/>
        public void RealizarConsultaSQLAsync(string codSentenca, int codColigada, string codAplicacao, string codUsuario, string parameters, object userState) {
            if ((this.RealizarConsultaSQLOperationCompleted == null)) {
                this.RealizarConsultaSQLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRealizarConsultaSQLOperationCompleted);
            }
            this.InvokeAsync("RealizarConsultaSQL", new object[] {
                        codSentenca,
                        codColigada,
                        codAplicacao,
                        codUsuario,
                        parameters}, this.RealizarConsultaSQLOperationCompleted, userState);
        }
        
        private void OnRealizarConsultaSQLOperationCompleted(object arg) {
            if ((this.RealizarConsultaSQLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RealizarConsultaSQLCompleted(this, new RealizarConsultaSQLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.totvs.com.br/br/RealizarConsultaSQLAuth", RequestNamespace="http://www.totvs.com.br/br/", ResponseNamespace="http://www.totvs.com.br/br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RealizarConsultaSQLAuth(string codSentenca, int codColigada, string codAplicacao, string Usuario, string Senha, string parameters) {
            object[] results = this.Invoke("RealizarConsultaSQLAuth", new object[] {
                        codSentenca,
                        codColigada,
                        codAplicacao,
                        Usuario,
                        Senha,
                        parameters});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RealizarConsultaSQLAuthAsync(string codSentenca, int codColigada, string codAplicacao, string Usuario, string Senha, string parameters) {
            this.RealizarConsultaSQLAuthAsync(codSentenca, codColigada, codAplicacao, Usuario, Senha, parameters, null);
        }
        
        /// <remarks/>
        public void RealizarConsultaSQLAuthAsync(string codSentenca, int codColigada, string codAplicacao, string Usuario, string Senha, string parameters, object userState) {
            if ((this.RealizarConsultaSQLAuthOperationCompleted == null)) {
                this.RealizarConsultaSQLAuthOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRealizarConsultaSQLAuthOperationCompleted);
            }
            this.InvokeAsync("RealizarConsultaSQLAuth", new object[] {
                        codSentenca,
                        codColigada,
                        codAplicacao,
                        Usuario,
                        Senha,
                        parameters}, this.RealizarConsultaSQLAuthOperationCompleted, userState);
        }
        
        private void OnRealizarConsultaSQLAuthOperationCompleted(object arg) {
            if ((this.RealizarConsultaSQLAuthCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RealizarConsultaSQLAuthCompleted(this, new RealizarConsultaSQLAuthCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void AutenticaAcessoAuthCompletedEventHandler(object sender, AutenticaAcessoAuthCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AutenticaAcessoAuthCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AutenticaAcessoAuthCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void AutenticaAcessoCompletedEventHandler(object sender, AutenticaAcessoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AutenticaAcessoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AutenticaAcessoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void RealizarConsultaSQLDataTableCompletedEventHandler(object sender, RealizarConsultaSQLDataTableCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RealizarConsultaSQLDataTableCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RealizarConsultaSQLDataTableCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void RealizarConsultaSQLDataTableAuthCompletedEventHandler(object sender, RealizarConsultaSQLDataTableAuthCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RealizarConsultaSQLDataTableAuthCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RealizarConsultaSQLDataTableAuthCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void RealizarConsultaSQLCompletedEventHandler(object sender, RealizarConsultaSQLCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RealizarConsultaSQLCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RealizarConsultaSQLCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void RealizarConsultaSQLAuthCompletedEventHandler(object sender, RealizarConsultaSQLAuthCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RealizarConsultaSQLAuthCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RealizarConsultaSQLAuthCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591